site_name: Docs Tamboerijn  Rinobot-Jaguar
site_url: https://rinobot-team.github.io/SPL-Docs/
repo_url: https://github.com/rinobot-team/SPL-Docs
repo_name: SPL-Docs
nav:
  - Home: index.md
  - Configuração:
    - Indice: config-projeto/README.md
    - Git: config-projeto/config-git.md
    - Projeto: config-projeto/config-projeto.md
    - Imagem & SDK: config-projeto/imagem-sdk.md
    - NAO: config-projeto/config-nao.md
    - Escrevendo Documentação: config-projeto/documentacao.md
  - Framework:
    - Indice: framework/README.md
    - Estrutura dos Diretórios: framework/directory-struct.md
    - Entry Point: framework/entry-point.md
    - Runtime: framework/runtime.md
    - Cyclers: framework/cyclers.md
    - Nós: framework/nodes.md
    - Base de Dados e Tipos: framework/databases-types.md
    - Parâmetros: framework/parameters.md
    - Comunicação: framework/communication.md
    - Interface com Hardware: framework/hardware-interface.md
    - Comunicação entre Threads: framework/thread-communication.md
    - Filtragem: framework/filtering.md
    - Macros: framework/macros.md
    - Tratamento de Erros: framework/error-handling.md
  - Ferramental:
    - Indice: ferramental/README.md
    - Pepsi:  ferramental/pepsi.md
    - Twix:  ferramental/twix.md
    - Recording & Replay:  ferramental/recording.md
    - Behaviour Simulation: ferramental/behaviour-sim.md
    - Aliveness:  ferramental/aliveness.md
  - Workflow:
    - Indice: workflow/README.md
    - Hello World: workflow/compilar-hello-world.md
    - Competições: workflow/competicao.md
    - Desenvolvimento: workflow/desenvolvimento.md
theme:
  name: readthedocs
locale: pt_BR
highlightjs: true
hljs_languages:
  - bash
  - rust