site_name: Docs Tamboerijn
site_url: https://rinobot-team.github.io/SPL-Docs/
repo_url: https://github.com/rinobot-team/SPL-Docs
repo_name: SPL-Docs
nav:
  - Home: index.md
  - Configuração:
    - Indice: config-projeto/README.md
    - Git: config-projeto/config-git.md
    - Projeto: config-projeto/config-projeto.md
    - Imagem & SDK: config-projeto/imagem-sdk.md
    - NAO: config-projeto/config-nao.md
    - Escrevendo Documentação: config-projeto/documentacao.md
    - Instalando OpenCV: config-projeto/config-opencv.md
  - Framework:
    - Indice: framework/README.md
    - Estrutura dos Diretórios: framework/directory-struct.md
    - Entry Point: framework/entry-point.md
    - Runtime: framework/runtime.md
    - Cyclers: framework/cyclers.md
    - Nós: framework/nodes.md
    - Base de Dados e Tipos: framework/databases-types.md
    - Parâmetros: framework/parameters.md
    - Comunicação: framework/communication.md
    - Interface com Hardware: framework/hardware-interface.md
    - Comunicação entre Threads: framework/thread-communication.md
    - Filtragem: framework/filtering.md
    - Macros: framework/macros.md
    - Tratamento de Erros: framework/error-handling.md
  - Workflow:
    - Indice: workflow/README.md
    - Hello World: workflow/compilar-hello-world.md
    - Competições: workflow/competicao.md
    - Desenvolvimento: workflow/desenvolvimento.md
    - Versionamento: workflow/versionamento.md
  - Sistema Operacional:
    - Indice: sistema-operacional/README.md
    - Particionamento: sistema-operacional/particionamento.md
    - Diretório Home: sistema-operacional/home-dir.md
    - Linux: sistema-operacional/linux.md
    - WiFi: sistema-operacional/wifi.md
    - HULA: sistema-operacional/hula.md
  - Robótica:
    - Indice: robotica/README.md
    - Sensoriamento:
      - Filtragem: robotica/sensoriamento/filtragem.md
      - Visão: robotica/sensoriamento/visao.md
      - Detecção de bola: robotica/sensoriamento/ball-detection.md
      - Áudio: robotica/sensoriamento/audio.md
    - Comportamento e Estratégia:
      - Comportamento: robotica/comportamento/comportamento.md
      - SPL Network: robotica/comportamento/spl-network.md
      - Estados do Robô: robotica/comportamento/estados_do_robo.md
    - Movimentação:
      - Planejamento de Passos: robotica/movimentacao/step-planning.md
      - Caminhar: robotica/movimentacao/caminhar.md
      - Chutar: robotica/movimentacao/chutar.md
      - Motion Files: robotica/movimentacao/motion-files.md
  - Ferramental:
    - Indice: ferramental/README.md
    - Pepsi:  ferramental/pepsi.md
    - Twix:  ferramental/twix.md
    - Recording & Replay:  ferramental/recording.md
    - Behaviour Simulation: ferramental/behaviour-sim.md
    - Aliveness:  ferramental/aliveness.md
    - Universal: ferramental/universal.md
theme:
  name: material
  logo: img/favicon.ico
  features:
    - content.code.annotate
    - content.tabs.link
    - navigation.indexes
    - navigation.tracking
  palette:
    - media: "(prefers-color-scheme: light)"
      primary: red
      scheme: default
      toggle:
        icon: material/weather-night
        name: Tema Escuro
    - media: "(prefers-color-scheme: dark)"
      primary: red
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Tema Claro
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.superfences
  - pymdownx.tilde
